/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/calc.check" instead.
 */

#include <check.h>

#include "tests_main.h"

START_TEST(invalid_input_test_1) {
  char input_str[7] = {"123+(3\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_2) {
  char input_str[7] = {"123x-3\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_3) {
  char input_str[7] = {"()\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_4) {
  char input_str[] = {"(123+2)+3)(3+2\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_5) {
  char input_str[] = {"(123+2)+3)3+2\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_6) {
  char input_str[] = {"12(3)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_7) {
  char input_str[] = {"123()\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_8) {
  char input_str[] = {"123+(-)(+)(*)(3)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_9) {
  char input_str[] = {"123*(3mod5)-()\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_10) {
  char input_str[] = {"(\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_11) {
  char input_str[] = {")\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_12) {
  char input_str[] = {"(123+2)+3cos(3)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_13) {
  char input_str[] = {"(123+2)+3cos(3)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_14) {
  char input_str[] = {"cos(tg(atan(sin(3+))))\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_15) {
  char input_str[] = {"cos(tg(atan(sin(3+))))\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_16) {
  char input_str[] = {"cos(tg(atan(sin(3+mod5))))\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_17) {
  char input_str[] = {"cos(tg(atan(sin(3+mod5))))\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_18) {
  char input_str[] = {"cos(tg(atan(sin(3+3mod5--3))))\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_19) {
  char input_str[] = {"cos(tg(atan(sin(3+3mod5--3))))\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_20) {
  char input_str[] = {"cos(tg(atan(sin(3+3mod5--3))))\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_21) {
  char input_str[] = {"cos+3\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_22) {
  char input_str[] = {"cos+3\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_23) {
  char input_str[] = {"cos+(3)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_26) {
  char input_str[] = {"cos(-)"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_27) {
  char input_str[] = {"cos(*/+-)"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_28) {
  char input_str[] = {"cos(cos(1.1.2))"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_29) {
  char input_str[] = {"cos(cos(2x))"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_30) {
  char input_str[] = {"123..3-2\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_31) {
  char input_str[] = {"123.3.2\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_32) {
  char input_str[] = {"123.3*.2\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_33) {
  char input_str[] = {"123.3*(.)2\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_34) {
  char input_str[] = {"123.3*(.)2\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_35) {
  char input_str[] = {"123.3+.2\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_36) {
  char input_str[] = {"123.3+32.(3+2)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_37) {
  char input_str[] = {"123.3+32.cos(3)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_38) {
  char input_str[] = {"123.3+32.tg(3)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_39) {
  char input_str[] = {"123.3+32.^3\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_40) {
  char input_str[] = {"3456+^3\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_43) {
  char input_str[] = {"3456+cos(3)-3+-^*/3mod5\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_44) {
  char input_str[] = {"cos(3+2-)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_45) {
  char input_str[] = {"cos(3+2-3^3mod3.4--3)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_46) {
  char input_str[] = {"45*(*28+31)\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_47) {
  char input_str[] = {
      "123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+"
      "123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+"
      "123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+123+"
      "123+123+123123+123+123+123+123+123+123+123+123+123+123\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "Enter less expression!");
}
END_TEST

START_TEST(invalid_input_test_48) {
  char input_str[] = {"+\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

START_TEST(invalid_input_test_49) {
  char input_str[] = {")\0"};
  char output_res[1024] = {'\0'};
  double x = 0;
  s21_calculator(input_str, output_res, x);
  ck_assert_str_eq(output_res, "INVALID INPUT");
}
END_TEST

Suite *tests_invalid_input() {
  Suite *s1 = suite_create("\033[45m-=INVALID INPUT=-\033[0m");
  TCase *tc1_1 = tcase_create("Numbers_and_brackets");
  TCase *tc1_2 = tcase_create("trigonometry_func");
  TCase *tc1_3 = tcase_create("dot");
  TCase *tc1_4 = tcase_create("math_operations");
  TCase *tc1_5 = tcase_create("check_input_more_255_symbols");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, invalid_input_test_1);
  tcase_add_test(tc1_1, invalid_input_test_2);
  tcase_add_test(tc1_1, invalid_input_test_3);
  tcase_add_test(tc1_1, invalid_input_test_4);
  tcase_add_test(tc1_1, invalid_input_test_5);
  tcase_add_test(tc1_1, invalid_input_test_6);
  tcase_add_test(tc1_1, invalid_input_test_7);
  tcase_add_test(tc1_1, invalid_input_test_8);
  tcase_add_test(tc1_1, invalid_input_test_9);
  tcase_add_test(tc1_1, invalid_input_test_10);
  tcase_add_test(tc1_1, invalid_input_test_11);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, invalid_input_test_12);
  tcase_add_test(tc1_2, invalid_input_test_13);
  tcase_add_test(tc1_2, invalid_input_test_14);
  tcase_add_test(tc1_2, invalid_input_test_15);
  tcase_add_test(tc1_2, invalid_input_test_16);
  tcase_add_test(tc1_2, invalid_input_test_17);
  tcase_add_test(tc1_2, invalid_input_test_18);
  tcase_add_test(tc1_2, invalid_input_test_19);
  tcase_add_test(tc1_2, invalid_input_test_20);
  tcase_add_test(tc1_2, invalid_input_test_21);
  tcase_add_test(tc1_2, invalid_input_test_22);
  tcase_add_test(tc1_2, invalid_input_test_23);
  tcase_add_test(tc1_2, invalid_input_test_26);
  tcase_add_test(tc1_2, invalid_input_test_27);
  tcase_add_test(tc1_2, invalid_input_test_28);
  tcase_add_test(tc1_2, invalid_input_test_29);
  suite_add_tcase(s1, tc1_3);
  tcase_add_test(tc1_3, invalid_input_test_30);
  tcase_add_test(tc1_3, invalid_input_test_31);
  tcase_add_test(tc1_3, invalid_input_test_32);
  tcase_add_test(tc1_3, invalid_input_test_33);
  tcase_add_test(tc1_3, invalid_input_test_34);
  tcase_add_test(tc1_3, invalid_input_test_35);
  tcase_add_test(tc1_3, invalid_input_test_36);
  tcase_add_test(tc1_3, invalid_input_test_37);
  tcase_add_test(tc1_3, invalid_input_test_38);
  tcase_add_test(tc1_3, invalid_input_test_39);
  suite_add_tcase(s1, tc1_4);
  tcase_add_test(tc1_4, invalid_input_test_40);
  tcase_add_test(tc1_4, invalid_input_test_43);
  tcase_add_test(tc1_4, invalid_input_test_44);
  tcase_add_test(tc1_4, invalid_input_test_45);
  tcase_add_test(tc1_4, invalid_input_test_46);
  suite_add_tcase(s1, tc1_5);
  tcase_add_test(tc1_5, invalid_input_test_47);
  tcase_add_test(tc1_5, invalid_input_test_48);
  tcase_add_test(tc1_5, invalid_input_test_49);

  return s1;
}
