/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/calculate.check" instead.
 */

#include <check.h>

#include "tests_main.h"

START_TEST(test_func_cos_1) {
  char input_str[] = {"cos(6)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.96017028665);
  free(output);
}
END_TEST

START_TEST(test_func_cos_2) {
  char input_str[] = {"cos(x)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -0.83907152907);
  free(output);
}
END_TEST

START_TEST(test_func_cos_3) {
  char input_str[] = {"cos(x+1)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.00442569798);
  free(output);
}
END_TEST

START_TEST(test_func_cos_4) {
  char input_str[] = {"cos(cos(tan(sin(log(5)))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.74399617566);
  free(output);
}
END_TEST

START_TEST(test_func_cos_5) {
  char input_str[] = {"cos(4*sin(3+tan(5)))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.08509852696);
  free(output);
}
END_TEST

START_TEST(test_func_cos_6) {
  char input_str[] = {"cos(5*6+cos(3))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -0.74137886347);
  free(output);

  // cos(2^5 × 3 + 5 ÷ 4)
}
END_TEST

START_TEST(test_func_cos_7) {
  char input_str[] = {"cos(2^5*3+5/4)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -0.990303397722);
  free(output);

  // cos(log(1 + 7 cos(5 ÷ 6 - sin(3))))
}
END_TEST

START_TEST(test_func_cos_8) {
  char input_str[] = {"cos(log(1*7*cos(5/6-sin(3))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.74417603836);
  free(output);
}
END_TEST

START_TEST(test_func_cos_9) {
  char input_str[] = {
      "cos(2+3-6*9/"
      "3)*cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)"
      "+cos(2)+cos(2)+cos(2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -5.3713931459991744);
  free(output);
}
END_TEST

START_TEST(test_func_cos_10) {
  char input_str[] = {
      "cos(2+3-6*9/"
      "3)*cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)+cos(2)"
      "+cos(2)+cos(2)+cos(2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -5.3713931459991744);
  free(output);

  // cos(cos(cos(cos(cos(cos(cos(cos(cos(6)))))))))
}
END_TEST

START_TEST(test_func_cos_11) {
  char input_str[] = {"cos(cos(cos(cos(cos(cos(cos(cos(cos(6)))))))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.74872611635);
  free(output);
}
END_TEST

START_TEST(test_func_cos_12) {
  char input_str[] = {"cos(3.5)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -0.93645668729);
  free(output);
}
END_TEST

START_TEST(test_func_acos_1) {
  char input_str[] = {"acos(0.92304912)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.394863401);
  free(output);
}
END_TEST

START_TEST(test_func_acos_2) {
  char input_str[] = {"acos(0.1)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.470628905633);
  free(output);
}
END_TEST

START_TEST(test_func_acos_3) {
  char input_str[] = {"acos(0.92304912)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.394863401);
  free(output);
}
END_TEST

START_TEST(test_func_acos_4) {
  char input_str[] = {"(acos(0.2+0.3)*acos(0.3-0.2))*(3+2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 7.700194943492007995963505);
  free(output);
}
END_TEST

START_TEST(test_func_acos_5) {
  char input_str[] = {"(acos(-1)+acos(2-1))+acos(0.9)-cos(2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 4.008766301933);
  free(output);
}
END_TEST

START_TEST(test_func_acos_nan_6) {
  char input_str[] = {"acos(2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_str_eq(output, "NAN");
  ck_assert_float_nan(number);
  free(output);
}
END_TEST

START_TEST(test_func_sin_1) {
  char input_str[] = {"sin(3)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.14112000806);
  free(output);
}
END_TEST

START_TEST(test_func_sin_2) {
  char input_str[] = {"sin(sin(sin(sin(sin(sin(sin(sin(sin(6)))))))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -0.253886750643);
  free(output);
}
END_TEST

START_TEST(test_func_sin_3) {
  char input_str[] = {"sin(sin(sin(sin(sin(sin(sin(sin(sin(x)))))))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -0.402600037904);
  free(output);

  // sin(sin(sin(3*sin(5))*tan(0.2)
}
END_TEST

START_TEST(test_func_sin_4) {
  char input_str[] = {"sin(sin(sin(3*sin(5))))*tan(0.2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -0.0518693109094759);
  free(output);

  // sin(sin(2)+sin(sin(sin(3)))*cos(2))
}
END_TEST

START_TEST(test_func_sin_5) {
  char input_str[] = {"sin(sin(2)+sin(sin(sin(3)))*cos(2))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.751912527704);
  free(output);
}
END_TEST

START_TEST(test_func_sin_6) {
  char input_str[] = {"sin(sin(2)+sin(sin(sin(3+x+5)))*cos(2))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 10;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.921424507586);
  free(output);
}
END_TEST

START_TEST(test_func_ln_1) {
  char input_str[] = {"ln(2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.69314718056);
  free(output);
}
END_TEST

START_TEST(test_func_ln_2) {
  char input_str[] = {"ln(0.2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -1.60943791243);
  free(output);
}
END_TEST

START_TEST(test_func_ln_nan_3) {
  char input_str[] = {"ln(-2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_str_eq(output, "NAN");
  ck_assert_float_nan(number);
  free(output);
}
END_TEST

START_TEST(test_func_ln_4) {
  char input_str[] = {"ln(-2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_str_eq(output, "NAN");
  ck_assert_float_nan(number);
  free(output);
}
END_TEST

START_TEST(test_func_ln_5) {
  char input_str[] = {"ln(47131231)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 17.6684464178);
  free(output);

  // ln(log(cos(25 - 3 ÷ 2)))
}
END_TEST

START_TEST(test_func_ln_6) {
  char input_str[] = {"ln(log(cos(25-3/2)))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_str_eq(output, "NAN");
  ck_assert_float_nan(number);
  free(output);
}
END_TEST

START_TEST(test_func_log_1) {
  char input_str[] = {"log(3)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.47712125472);
  free(output);
}
END_TEST

START_TEST(test_func_log_nan_2) {
  char input_str[] = {"log(-3)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_str_eq(output, "NAN");
  ck_assert_float_nan(number);
  free(output);
}
END_TEST

START_TEST(test_func_log_3) {
  char input_str[] = {"log(ln(7))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.28912278317);
  free(output);
}
END_TEST

START_TEST(test_func_log_inf_4) {
  char input_str[] = {"log(0)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_str_eq(output, "INF");
  ck_assert_float_infinite(number);
  free(output);
}
END_TEST

START_TEST(test_func_log_5) {
  char input_str[] = {"log(3.5)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.54406804435);
  free(output);
}
END_TEST

START_TEST(test_func_asin_1) {
  char input_str[] = {"asin(0.92304912)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.175932925);
  free(output);
}
END_TEST

START_TEST(test_func_asin_2) {
  char input_str[] = {"asin(0.92304912)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.175932925);
  free(output);
}
END_TEST

START_TEST(test_func_asin_3) {
  char input_str[] = {"asin(-0.998)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -1.50754022792);
  free(output);
}
END_TEST

START_TEST(test_func_asin_nan_4) {
  char input_str[] = {"asin(-1.05)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_str_eq(output, "NAN");
  ck_assert_float_nan(number);
  free(output);
}
END_TEST

START_TEST(test_func_sqrt_1) {
  char input_str[] = {"sqrt(123456)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 351.363060096);
  free(output);
}
END_TEST

START_TEST(test_func_sqrt_2) {
  char input_str[] = {"sqrt(0)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0);
  free(output);
}
END_TEST

START_TEST(test_func_sqrt_nan_3) {
  char input_str[] = {"sqrt(-0.002)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_str_eq(output, "NAN");
  ck_assert_float_nan(number);
  free(output);
}
END_TEST

START_TEST(test_func_sqrt_3) {
  char input_str[] = {"sqrt(sqrt(sqrt(sqrt(sqrt(sqrt(2334))))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.1288248873729899);
  free(output);

  // sqrt(sqrt(sqrt(sqrt(sqrt(sqrt(123123.123123123))))))
}
END_TEST

START_TEST(test_func_sqrt_4) {
  char input_str[] = {"sqrt(sqrt(sqrt(sqrt(sqrt(sqrt(123123.123123123))))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.2009821610869789);
  free(output);

  // sqrt(sqrt(sqrt(sqrt(sqrt(sqrt(123123.12312312312312312313))))))
}
END_TEST

START_TEST(test_func_sqrt_5) {
  char input_str[] = {
      "sqrt(sqrt(sqrt(sqrt(sqrt(sqrt(356789.1231231231231231231356))))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.2211146211547692615768437);
  free(output);

  // sqrt(sqrt(sqrt(sqrt(sqrt(sqrt(356789123123.1231231231231231231356))))))
}
END_TEST

START_TEST(test_func_sqrt_6) {
  char input_str[] = {
      "sqrt(sqrt(sqrt(sqrt(sqrt(sqrt(356789123123.1231231231231231231356))))))"
      "\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.5153272435969838);
  free(output);
}
END_TEST

START_TEST(test_func_tan_1) {
  char input_str[] = {"tan(123456)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.10112909392);
  free(output);
}
END_TEST

START_TEST(test_func_tan_2) {
  char input_str[] = {"tan(tan(tan(3*3)))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -0.528151397117);
  free(output);
}
END_TEST

START_TEST(test_func_atan_1) {
  char input_str[] = {"atan(123456)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.570788227);
  free(output);
}
END_TEST

START_TEST(test_math_mod_1) {
  char input_str[] = {"3mod5\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 3);
  free(output);
}
END_TEST

START_TEST(test_math_mod_2) {
  char input_str[] = {"3mod5*3+2\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 11);
  free(output);
}
END_TEST

START_TEST(test_math_mod_3) {
  char input_str[] = {"3*3mod5*3+2\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 14);
  free(output);
}
END_TEST

START_TEST(test_math_number_1) {
  char input_str[] = {"3\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 3);
  free(output);
}
END_TEST

START_TEST(test_math_number_2) {
  char input_str[] = {"1.2323232322\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1.2323232322);
  free(output);
}
END_TEST

START_TEST(test_math_plus_minus_div_mult_mod_exp) {
  char input_str[] = {"(1.2+2)*3+2*3mod5-4/1^3*tan(3+2)^3\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 165.128502406752086235022440570776924892);
  free(output);
}
END_TEST

START_TEST(test_big_numbers_1) {
  char input_str[] = {"1231231.565656565656565656^2\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1515931168269.117947148248785644771);
  free(output);
}
END_TEST

START_TEST(test_big_numbers_2) {
  char input_str[] = {
      "1231231.565656565656565656^2+1231231.565656565656565656^2 \0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 3031862336538.235894296497571289542);
  free(output);
}
END_TEST

START_TEST(test_big_numbers_3) {
  char input_str[] = {
      "1231231.565656565656565656^2+1231231.565656565656565656^2-1231231."
      "565656565656565656^2/1231231.565656565656565656^2\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 3031862336537.235894296497571289541883481277421);
  free(output);
}
END_TEST

START_TEST(test_small_numbers_1) {
  char input_str[] = {"cos(0.00000000001232560000012300123)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 1);
  free(output);
}
END_TEST

START_TEST(test_small_numbers_2) {
  char input_str[] = {
      "cos(cos(cos(cos(cos(cos(cos(cos(cos(0.00000000001232560000012300123)))))"
      "))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.750417761764);
  free(output);

  // sin(cos(tan(atan(acos(asin(ln(1))))))
}
END_TEST

START_TEST(test_small_numbers_3) {
  char input_str[] = {"sin(cos(tan(atan(acos(asin(ln(1))))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0);
  free(output);
}
END_TEST

START_TEST(test_small_numbers_4) {
  char input_str[] = {"sin(cos(tan(atan(acos(asin(ln(2)))))))\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.693147180559);
  free(output);
}
END_TEST

START_TEST(test_math_unary_plus_1) {
  char input_str[] = {"+2\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 2);
  free(output);
}
END_TEST

START_TEST(test_math_unary_minus_2) {
  char input_str[] = {"-2\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -2);
  free(output);
}
END_TEST

START_TEST(test_math_unary_minus_3) {
  char input_str[] = {"-tan(3)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 0.142546543074);
  free(output);
}
END_TEST

START_TEST(test_math_unary_plus_3) {
  char input_str[] = {"cos(+2)\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -0.41614683654);
  free(output);
}
END_TEST

START_TEST(test_math_unary_plus_4) {
  char input_str[] = {"-2*cos(+2-2)^+3\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, -2);
  free(output);
}
END_TEST

START_TEST(test_math_unary_minus_4) {
  char input_str[] = {"-2*cos(-2-2)^-3\0"};
  int n_str = strlen(input_str) * 2;
  char *output = (char *)malloc(sizeof(char) * n_str);
  if (output != NULL) {
    output[n_str] = '\0';
  }
  double x = 0;
  double number = 0.0;
  number = s21_calculator(input_str, output, x);
  ck_assert_float_eq(number, 7.1615481193407875);
  free(output);
}
END_TEST

Suite *tests_calculate() {
  Suite *s1 = suite_create("\033[45m-=CALCULATE=-\033[0m");
  TCase *tc1_1 = tcase_create("trigonometry_func");
  TCase *tc1_2 = tcase_create("math_func");
  TCase *tc1_3 = tcase_create("big_numbers");
  TCase *tc1_4 = tcase_create("small_numbers");
  TCase *tc1_5 = tcase_create("unary_sign_check");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_func_cos_1);
  tcase_add_test(tc1_1, test_func_cos_2);
  tcase_add_test(tc1_1, test_func_cos_3);
  tcase_add_test(tc1_1, test_func_cos_4);
  tcase_add_test(tc1_1, test_func_cos_5);
  tcase_add_test(tc1_1, test_func_cos_6);
  tcase_add_test(tc1_1, test_func_cos_7);
  tcase_add_test(tc1_1, test_func_cos_8);
  tcase_add_test(tc1_1, test_func_cos_9);
  tcase_add_test(tc1_1, test_func_cos_10);
  tcase_add_test(tc1_1, test_func_cos_11);
  tcase_add_test(tc1_1, test_func_cos_12);
  tcase_add_test(tc1_1, test_func_acos_1);
  tcase_add_test(tc1_1, test_func_acos_2);
  tcase_add_test(tc1_1, test_func_acos_3);
  tcase_add_test(tc1_1, test_func_acos_4);
  tcase_add_test(tc1_1, test_func_acos_5);
  tcase_add_test(tc1_1, test_func_acos_nan_6);
  tcase_add_test(tc1_1, test_func_sin_1);
  tcase_add_test(tc1_1, test_func_sin_2);
  tcase_add_test(tc1_1, test_func_sin_3);
  tcase_add_test(tc1_1, test_func_sin_4);
  tcase_add_test(tc1_1, test_func_sin_5);
  tcase_add_test(tc1_1, test_func_sin_6);
  tcase_add_test(tc1_1, test_func_ln_1);
  tcase_add_test(tc1_1, test_func_ln_2);
  tcase_add_test(tc1_1, test_func_ln_nan_3);
  tcase_add_test(tc1_1, test_func_ln_4);
  tcase_add_test(tc1_1, test_func_ln_5);
  tcase_add_test(tc1_1, test_func_ln_6);
  tcase_add_test(tc1_1, test_func_log_1);
  tcase_add_test(tc1_1, test_func_log_nan_2);
  tcase_add_test(tc1_1, test_func_log_3);
  tcase_add_test(tc1_1, test_func_log_inf_4);
  tcase_add_test(tc1_1, test_func_log_5);
  tcase_add_test(tc1_1, test_func_asin_1);
  tcase_add_test(tc1_1, test_func_asin_2);
  tcase_add_test(tc1_1, test_func_asin_3);
  tcase_add_test(tc1_1, test_func_asin_nan_4);
  tcase_add_test(tc1_1, test_func_sqrt_1);
  tcase_add_test(tc1_1, test_func_sqrt_2);
  tcase_add_test(tc1_1, test_func_sqrt_nan_3);
  tcase_add_test(tc1_1, test_func_sqrt_3);
  tcase_add_test(tc1_1, test_func_sqrt_4);
  tcase_add_test(tc1_1, test_func_sqrt_5);
  tcase_add_test(tc1_1, test_func_sqrt_6);
  tcase_add_test(tc1_1, test_func_tan_1);
  tcase_add_test(tc1_1, test_func_tan_2);
  tcase_add_test(tc1_1, test_func_atan_1);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, test_math_mod_1);
  tcase_add_test(tc1_2, test_math_mod_2);
  tcase_add_test(tc1_2, test_math_mod_3);
  tcase_add_test(tc1_2, test_math_number_1);
  tcase_add_test(tc1_2, test_math_number_2);
  tcase_add_test(tc1_2, test_math_plus_minus_div_mult_mod_exp);
  suite_add_tcase(s1, tc1_3);
  tcase_add_test(tc1_3, test_big_numbers_1);
  tcase_add_test(tc1_3, test_big_numbers_2);
  tcase_add_test(tc1_3, test_big_numbers_3);
  suite_add_tcase(s1, tc1_4);
  tcase_add_test(tc1_4, test_small_numbers_1);
  tcase_add_test(tc1_4, test_small_numbers_2);
  tcase_add_test(tc1_4, test_small_numbers_3);
  tcase_add_test(tc1_4, test_small_numbers_4);
  suite_add_tcase(s1, tc1_5);
  tcase_add_test(tc1_5, test_math_unary_plus_1);
  tcase_add_test(tc1_5, test_math_unary_minus_2);
  tcase_add_test(tc1_5, test_math_unary_minus_3);
  tcase_add_test(tc1_5, test_math_unary_plus_3);
  tcase_add_test(tc1_5, test_math_unary_plus_4);
  tcase_add_test(tc1_5, test_math_unary_minus_4);

  return s1;
}
